export const AUTH_OPTIONS = 'AUTH_OPTIONS';
export const AUTH_SESSION_OPTIONS = 'AUTH_SESSION_OPTIONS';
export const AUTH_CONFIG_OPTIONS = 'AUTH_CONFIG_OPTIONS';
export const SESSION_MIDDLEWARE = 'SESSION_MIDDLEWARE';
export const SESSION_MIDDLEWARE_OPTIONS = 'SESSION_MIDDLEWARE_OPTIONS';
